api/urls.py
from django.urls import path, include


urlpatterns = [
    path('v1/', include('api.v1.urls')),
]

cart/urls.py
from django.conf.urls import url
from django.urls import path

from .views import (
    cart_add,
    cart_detail,
    cart_remove,
    send_mail_cart,
    cart_opt
    )


app_name = 'carts'

urlpatterns = [
    path('cart/detail/', cart_detail, name="cart_detail"),  # /cart/detail
    path('cart/add/<product_id>/', cart_add, name="cart_add"),  # /cart/add
    path('cart/opt/<str:product_id>/', cart_opt, name="cart_opt"),  # /cart/opt
    path('cart/delete/<product_id>/', cart_remove, name="cart_remove"),  # /cart/delete
    path('cart/send/', send_mail_cart, name="cart_send"),  # /cart/send
]

projectMarket/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


from accounts.views import UserRegisterView

from products.views import ProductListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', ProductListView.as_view(), name="home"),
    path('products/', include('products.urls', namespace='product')),
    path('categories/', include('categories.urls', namespace='category')),
    path('companies/', include('companies.urls', namespace='company')),
    path('aktuels/', include('aktuels.urls', namespace='aktuel')),
    path('carts/', include('cart.urls', namespace='cart')),

    path('api/', include('api.urls')),
    path('register/', UserRegisterView.as_view(), name="register"),

    path('', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('', include('accounts.urls', namespace='profile')),
]


if settings.DEBUG: 
    #urlpatterns += ((static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType

class Cart(models.Model):
    creation_date = models.DateTimeField(verbose_name=_('creation date'))
    checked_out = models.BooleanField(default=False, verbose_name=_('checked out'))

    class Meta:
        verbose_name = _('Sepet')
        verbose_name_plural = _('Sepetler')
        ordering = ('-creation_date',)

    def __unicode__(self):
        return unicode(self.creation_date)

class ItemManager(models.Manager):
    def get(self, *args, **kwargs):
        if 'products' in kwargs:
            kwargs['content_type'] = ContentType.objects.get_for_model(type(kwargs['products']))
            kwargs['object_id'] = kwargs['products'].pk
            del(kwargs['products'])
        return super(ItemManager, self).get(*args, **kwargs)

class Item(models.Model):
    cart = models.ForeignKey(Cart, verbose_name=_('cart'), on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name=_('quantity'))
    unit_price = models.DecimalField(max_digits=18, decimal_places=2, verbose_name=_('unit price'))
    # product as generic relation
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()

    objects = ItemManager()

    class Meta:
        verbose_name = _('item')
        verbose_name_plural = _('items')
        ordering = ('cart',)

    def __unicode__(self):
        return u'%d units of %s' % (self.quantity, self.product.__class__.__name__)

    def total_price(self):
        return self.quantity * self.unit_price
    total_price = property(total_price)

    # product
    def get_product(self):
        return self.content_type.get_object_for_this_type(pk=self.object_id)

    def set_product(self, product):
        self.content_type = ContentType.objects.get_for_model(type(product))
        self.object_id = product.pk

    product = property(get_product, set_product)

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class QuantityForm(forms.Form):
    quantity = forms.IntegerField(label='Adet')
    product_id = forms.IntegerField(label='Ürün Id')

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from products.models import Product
from .cart import Cart
from cart.forms import CartAddProductForm, QuantityForm
from projectMarket.settings import EMAIL_HOST_USER
from django.core.mail import send_mail


def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product=product)
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = global_cart_detail(request)
    return render(request, 'carts/detail.html', {'carts': cart})


def cart_opt(request, product_id):
    quantity = QuantityForm(request.POST).data["quantity"]
    cart = Cart(request)
    product = get_object_or_404(Product, id=int(product_id))
    cart.update(product, quantity)
    return redirect('cart:cart_detail')


def global_cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return cart


def send_mail_cart(request):
    try:
        send_mail("selam", "", EMAIL_HOST_USER, ["testuser@gmail.com"], fail_silently=False)
    except:
        raise BaseException("E-posta gönderilirken bir hata oluştu.")

templates/carts/cart.html
{% extends 'base.html' %}

{% block body %}
    <table>
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Total Price</th>
        </tr>
        {% for item in cart %}
        <tr>
            <td>{{ item.product.name }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.total_price }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/carts/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Sepetim |
{% endblock %}


{% block content %}

<style type="text/css">
    .btn-primary:hover{
        background-color:#f26667;
        border-color: #f26667;
    }
    table > tbody > tr > td{


    }
</style>
    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h3><b>Alışveriş Listem</b>
            <span class="badge pull-right">
                {% with totail_items=carts|length %}
                    {% if carts|length > 0 %}
                        Sepetimdekiler:
                        <a href="{% url "cart:cart_detail" %}" style="color: #ffffff; font-size:15px;">
                            {{ totail_items }} Ürün {{ totail_items|pluralize }}, TL. {{ carts.get_total_price }}
                        </a>
                        {% else %}
                        Sepetiniz boş.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
            <table class="table table-striped table-hover">
                <thead style="background-color: #f26667">
                    <tr>
                        <th>Resim</th>
                        <th>Ürün</th>
                        <th>Fiyat</th>
                        <th style="padding-right: 2px; padding-left: 2px; width: 15%;">	Miktar</th>
                        <th style="width:10%;">Sil</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in carts %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get__absolute_url }}">
                                    <div class="cartdetailimg">
                                        <img src="/media/{{ product.image_prod_first }}" alt="...">
                                    </div>
                                </a>
                            </td>
                            <td class="align-text-middle"><span>{{ product.name }}</span></td>
                            <td>{{ item.total_price }} TL</td>
                            <td>
                                <form action="{% url "cart:cart_opt" product.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="number" step="1" value="{{ item.quantity }}" name="quantity" style="width: 50%;" onchange="clickButton({{ product.id }})">
                                    <input style="display: none;" type="number" value="{{ product.id }}" name="product_id">
                                    <input style="display: none;" type="submit" id="submitButton{{ product.id }}" value="Güncelle" class="btn btn-primary">
                                </form>
                            </td>
                            <td>
                                <a href="{% url "cart:cart_remove" product.id %}" class="btn btn-primary">Sil</a>
                            </td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #f26667">
                    <td><b>Toplam</b></td>
                    <td colspan="3"></td>
                    <td colspan="num"><b>{{ carts.get_total_price }} TL</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">
            <form action="{% url "cart:cart_send" %}" method="post">
                {% csrf_token %}
                <input type="email">
                <input type="submit" value="Gönder" class="btn btn-primary">
            </form>

        </p>
        </div>
    </div>

<script>
    function clickButton(product_id) {
        document.getElementById("submitButton" + product_id).click();
    }
</script>
{% endblock %}